### ISSUE TITLE
Middle field -1 in lab files created by XWaveLabelSerializer

### ISSUE THREAD

**Issue by insa-k** [m2ci-msp/jtgt#10]
this issue is a follow up to this [issue](https://github.com/marytts/marytts/issues/811)
## Behavior 
described in detail [here](https://github.com/marytts/marytts/issues/811)

```
separator ;
nfields 1
#
     0.38 -1 _
     0.47 -1 n
     0.57 -1 A
...
```
TL;DR
The middle field ```-1``` (added in **XWaveLabelSerializer.java**, ln. 135) affects other programs when working with these lab files.

The standard for Praat is a ```26``` there. Is there a specific reason for having a ```-1``` instead of ```26``` which would imitate the Praat-approach? 
This is the first time I've seen that the middle field of the lab file affects the behavior of another program but this might not be a singular problem.

**Comment by seblemaguer** [comment]
nop there is no specific reason. I was told that the middle field is basically unused normally. I'm not against changing it as soon as we know exactly what it corresponds to.
